#![recursion_limit = "1024"]
pub mod github;
mod lints;
mod make;
mod scripts;
mod utils;

pub use lints::LINTS;
pub use scripts::programs::{Settings as ScriptSettings, set_settings as set_script_settings};
pub use scripts::{
    Kind, Lang, StoredScript, content_hash, export_script_cache, fix_text, import_script_cache,
    nixstr::NIX_ESCAPING, prefetch, prefetch_scripts, referenced_files, script_cache_changed,
    shell_scripts, take_dependencies, tool_versions, with_current_file,
};

use rnix::{ParseError, SyntaxElement, SyntaxKind, TextRange};
use std::{convert::Into, default::Default};

use serde::{
    Serialize,
    ser::{SerializeStruct, Serializer},
};

#[derive(Debug, Default, Serialize)]
pub enum Severity {
    #[default]
    Warn,
    Error,
    Hint,
}

/// Report generated by a lint
#[derive(Debug, Default, Serialize)]
pub struct Report {
    // The unique name of this lint
    pub name: &'static str,
    /// General information about this lint and where it applies.
    pub note: &'static str,
    /// An error code to uniquely identify this lint
    pub code: u32,
    /// Report severity level
    pub severity: Severity,
    /// Collection of diagnostics raised by this lint
    pub diagnostics: Vec<Diagnostic>,
}

impl Report {
    /// Construct a report. Do not invoke `Report::new` manually, see `lint` macro
    #[must_use]
    pub fn new(name: &'static str, note: &'static str, code: u32) -> Self {
        Self {
            name,
            note,
            code,
            ..Default::default()
        }
    }
    /// Add a diagnostic to this report
    #[allow(clippy::return_self_not_must_use)]
    pub fn diagnostic<S: AsRef<str>>(mut self, at: TextRange, message: S) -> Self {
        self.diagnostics.push(Diagnostic::new(at, message));
        self
    }
    /// Add a diagnostic with instructions for fixing it by hand
    #[allow(clippy::return_self_not_must_use)]
    pub fn diagnostic_with_help<S: AsRef<str>>(
        mut self,
        at: TextRange,
        message: S,
        help: String,
    ) -> Self {
        let mut diagnostic = Diagnostic::new(at, message);
        diagnostic.help = Some(help);
        self.diagnostics.push(diagnostic);
        self
    }
    /// Add a diagnostic about another file that `statix fix` resolves
    #[allow(clippy::return_self_not_must_use)]
    pub fn external_fixed_later<S: AsRef<str>>(
        mut self,
        at: TextRange,
        message: S,
        external: External,
    ) -> Self {
        let mut diagnostic = Diagnostic::new(at, message);
        diagnostic.fixed_later = true;
        diagnostic.external = Some(external);
        self.diagnostics.push(diagnostic);
        self
    }
    /// Add a diagnostic about another file, with instructions for fixing it
    #[allow(clippy::return_self_not_must_use)]
    pub fn external_with_help<S: AsRef<str>>(
        mut self,
        at: TextRange,
        message: S,
        help: String,
        external: External,
    ) -> Self {
        let mut diagnostic = Diagnostic::new(at, message);
        diagnostic.help = Some(help);
        diagnostic.external = Some(external);
        self.diagnostics.push(diagnostic);
        self
    }
    /// Add a diagnostic that `statix fix` resolves in a later pass
    #[allow(clippy::return_self_not_must_use)]
    pub fn diagnostic_fixed_later<S: AsRef<str>>(mut self, at: TextRange, message: S) -> Self {
        let mut diagnostic = Diagnostic::new(at, message);
        diagnostic.fixed_later = true;
        self.diagnostics.push(diagnostic);
        self
    }
    /// Add a diagnostic with a fix to this report
    #[allow(clippy::return_self_not_must_use)]
    pub fn suggest<S: AsRef<str>>(
        mut self,
        at: TextRange,
        message: S,
        suggestion: Suggestion,
    ) -> Self {
        self.diagnostics
            .push(Diagnostic::suggest(at, message, suggestion));
        self
    }
    /// Set severity level
    #[allow(clippy::return_self_not_must_use, clippy::must_use_candidate)]
    pub fn severity(mut self, severity: Severity) -> Self {
        self.severity = severity;
        self
    }
    /// A range that encompasses all the suggestions provided in this report
    pub fn total_suggestion_range(&self) -> Option<TextRange> {
        self.diagnostics
            .iter()
            .filter_map(|d| Some(d.suggestion.as_ref()?.at))
            .reduce(rnix::TextRange::cover)
    }
    /// A range that encompasses all the diagnostics provided in this report
    pub fn total_diagnostic_range(&self) -> Option<TextRange> {
        self.diagnostics
            .iter()
            .map(|d| d.at)
            .reduce(rnix::TextRange::cover)
    }
    /// Unsafe but handy replacement for above
    #[must_use]
    pub fn range(&self) -> TextRange {
        self.total_suggestion_range()
            .expect("range() is only called on reports with suggestions")
    }
    /// Apply all diagnostics. Assumption: diagnostics do not overlap
    pub fn apply(&self, src: &mut String) {
        for d in &self.diagnostics {
            d.apply(src);
        }
    }
    /// Create a report out of a parse error
    #[must_use]
    pub fn from_parse_err(err: &ParseError) -> Self {
        let at = match err {
            ParseError::Unexpected(at)
            | ParseError::UnexpectedExtra(at)
            | ParseError::UnexpectedWanted(_, at, _)
            | ParseError::UnexpectedDoubleBind(at)
            | ParseError::DuplicatedArgs(at, _) => at,
            ParseError::UnexpectedEOF
            | ParseError::UnexpectedEOFWanted(_)
            | ParseError::RecursionLimitExceeded => &TextRange::empty(0u32.into()),
            _ => panic!(
                "if this happened to you, please report an issue titled \"wild ParseError variant appeared\""
            ),
        };
        let mut message = err.to_string();
        message
            .as_mut_str()
            .get_mut(0..1)
            .map(str::make_ascii_uppercase);
        Self::new("syntax_error", "Syntax error", 0)
            .diagnostic(*at, message)
            .severity(Severity::Error)
    }
}

/// Mapping from a bytespan to an error message.
/// Can optionally suggest a fix.
#[derive(Debug)]
pub struct Diagnostic {
    pub at: TextRange,
    pub message: String,
    pub suggestion: Option<Suggestion>,
    /// How to fix it by hand (or by an agent) when there is no suggestion.
    pub help: Option<String>,
    /// `statix fix` fixes it in a later pass although it has no suggestion yet.
    pub fixed_later: bool,
    /// Where the problem really is, when it's in another file.
    pub external: Option<External>,
}

/// A position in a file other than the one being linted.
#[derive(Debug, Clone)]
pub struct External {
    pub path: std::path::PathBuf,
    pub line: usize,
    pub column: usize,
}

impl Diagnostic {
    /// Construct a diagnostic.
    pub fn new<S: AsRef<str>>(at: TextRange, message: S) -> Self {
        Self {
            at,
            message: message.as_ref().into(),
            suggestion: None,
            help: None,
            fixed_later: false,
            external: None,
        }
    }
    /// Construct a diagnostic with a fix.
    pub fn suggest<S: AsRef<str>>(at: TextRange, message: S, suggestion: Suggestion) -> Self {
        Self {
            at,
            message: message.as_ref().into(),
            suggestion: Some(suggestion),
            help: None,
            fixed_later: false,
            external: None,
        }
    }
    /// Whether `statix fix` takes care of it.
    #[must_use]
    pub fn is_fixable(&self) -> bool {
        self.suggestion.is_some() || self.fixed_later
    }
    /// Apply a diagnostic to a source file
    pub fn apply(&self, src: &mut String) {
        if let Some(s) = &self.suggestion {
            s.apply(src);
        }
    }
}

impl Serialize for Diagnostic {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut s = serializer.serialize_struct("Diagnostic", 3)?;
        let at = {
            let start = usize::from(self.at.start());
            let end = usize::from(self.at.end());
            (start, end)
        };
        s.serialize_field("at", &at)?;
        s.serialize_field("message", &self.message)?;
        if let Some(suggestion) = &self.suggestion {
            s.serialize_field("suggestion", suggestion)?;
        }
        if let Some(help) = &self.help {
            s.serialize_field("help", help)?;
        }
        s.serialize_field("fixable", &self.is_fixable())?;
        s.end()
    }
}

#[derive(Debug)]
pub enum Replacement {
    Empty,
    SyntaxElement(SyntaxElement),
}

/// Suggested fix for a diagnostic, the fix is provided as a syntax element.
/// Look at `make.rs` to construct fixes.
#[derive(Debug)]
pub struct Suggestion {
    pub at: TextRange,
    pub fix: Replacement,
}

impl std::fmt::Display for Replacement {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Replacement::Empty => Ok(()),
            Replacement::SyntaxElement(syntax_element) => write!(f, "{syntax_element}"),
        }
    }
}

impl Suggestion {
    #[must_use]
    pub fn with_replacement(at: TextRange, fix: impl Into<SyntaxElement>) -> Self {
        Self {
            at,
            fix: Replacement::SyntaxElement(fix.into()),
        }
    }
    #[must_use]
    pub fn with_empty(at: TextRange) -> Self {
        Self {
            at,
            fix: Replacement::Empty,
        }
    }
    /// Apply a suggestion to a source file
    pub fn apply(&self, src: &mut String) {
        let start = usize::from(self.at.start());
        let end = usize::from(self.at.end());
        src.replace_range(start..end, &self.fix.to_string());
    }
}

unsafe impl Send for Suggestion {}

impl Serialize for Suggestion {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut s = serializer.serialize_struct("Suggestion", 2)?;
        let at = {
            let start = usize::from(self.at.start());
            let end = usize::from(self.at.end());
            (start, end)
        };
        let fix = self.fix.to_string();
        s.serialize_field("at", &at)?;
        s.serialize_field("fix", &fix)?;
        s.end()
    }
}

/// Lint logic is defined via this trait. Do not implement manually,
/// look at the `lint` attribute macro instead for implementing rules
pub trait Rule {
    fn validate(&self, node: &SyntaxElement) -> Option<Report>;
    /// Several reports for one node (e.g. warnings and hints apart, as
    /// severity is per report).
    fn validate_all(&self, node: &SyntaxElement) -> Vec<Report> {
        self.validate(node).into_iter().collect()
    }
}

/// Contains information about the lint itself. Do not implement manually,
/// look at the `lint` attribute macro instead for implementing rules
pub trait Metadata {
    fn name(&self) -> &'static str;
    fn note(&self) -> &'static str;
    fn code(&self) -> u32;
    fn report(&self) -> Report;
    fn match_with(&self, with: &SyntaxKind) -> bool;
    fn match_kind(&self) -> Vec<SyntaxKind>;
}

/// Contains offline explanation for each lint
/// The `lint` macro scans nearby doc comments for
/// explanations and derives this trait.
///
pub trait Explain {
    fn explanation(&self) -> &'static str {
        "no explanation found"
    }
}

/// Combines Rule and Metadata, do not implement manually, this is derived by
/// the `lint` macro.
pub trait Lint: Metadata + Explain + Rule + Send + Sync {}

/// Helper utility to take lints from modules and insert them into a map for efficient
/// access. Mapping is from a `SyntaxKind` to a list of lints that apply on that Kind.
///
/// See `lints.rs` for usage.
#[macro_export]
macro_rules! lints {
    ($($s:ident),*,) => {
        lints!($($s),*);
    };
    ($($s:ident),*) => {
        $(
            mod $s;
        )*
        ::lazy_static::lazy_static! {
            pub static ref LINTS: Vec<&'static Box<dyn $crate::Lint>> = {
                let mut v = Vec::new();
                $(
                    {
                        let temp_lint = &*$s::LINT;
                        v.push(temp_lint);
                    }
                )*
                v
            };
        }
    }
}
