use crate::lints;

lints! {
    bool_comparison,
    empty_let_in,
    manual_inherit,
    manual_inherit_from,
    legacy_let_syntax,
    collapsible_let_in,
    eta_reduction,
    useless_parens,
    // unquoted_splice,
    empty_pattern,
    redundant_pattern_bind,
    unquoted_uri,
    empty_inherit,
    deprecated_to_path,
    bool_simplification,
    useless_has_attr,
    repeated_keys,
    empty_list_concat,
    devenv_exec_shebang,
    devenv_pre_commit,
    hardcoded_store_path,
    impure_host_path,
    shellcheck,
    ruff,
    script_file,
    undeclared_command,
    structured_text_file,
    shell_idiom,
    embedded_code,
    packaged_in_nixpkgs
}
