//! Shell builtins (not commands a script depends on).

/// bash 5 `compgen -b` (resholve's list).
pub(super) const BASH_BUILTINS: &[&str] = &[
    ".",
    ":",
    "[",
    "alias",
    "bg",
    "bind",
    "break",
    "builtin",
    "caller",
    "cd",
    "command",
    "compgen",
    "complete",
    "compopt",
    "continue",
    "declare",
    "dirs",
    "disown",
    "echo",
    "enable",
    "eval",
    "exec",
    "exit",
    "export",
    "false",
    "fc",
    "fg",
    "getopts",
    "hash",
    "help",
    "history",
    "jobs",
    "kill",
    "let",
    "local",
    "logout",
    "mapfile",
    "popd",
    "printf",
    "pushd",
    "pwd",
    "read",
    "readarray",
    "readonly",
    "return",
    "set",
    "shift",
    "shopt",
    "source",
    "suspend",
    "test",
    "times",
    "trap",
    "true",
    "type",
    "typeset",
    "ulimit",
    "umask",
    "unalias",
    "unset",
    "wait",
];

/// dash builtins, used for `sh` and `dash` scripts.
pub(super) const DASH_BUILTINS: &[&str] = &[
    ".", ":", "[", "alias", "bg", "break", "cd", "chdir", "command", "continue", "echo", "eval",
    "exec", "exit", "export", "false", "fc", "fg", "getopts", "hash", "jobs", "kill", "local",
    "printf", "pwd", "read", "readonly", "return", "set", "shift", "test", "times", "trap", "true",
    "type", "ulimit", "umask", "unalias", "unset", "wait",
];
